const QUERY_KEYS = {
  POST: 'postDetail/post',
  COMMENTS: 'postDetail/comments',
  LIKE: 'postDetail/like',
  UNLIKE: 'postDetail/unlike',
  USER_INFO: 'postDetail/user',
  COMMENT_LIKE: 'postDetail/commentItem/like',
  COMMENT_UNLIKE: 'postDetail/commentItem/unlike',
  GET_QUESTION: 'get/question/questionDetail',
  POST_ANSWER: 'post/answer/questionDetail',
  MY_LEVEL: 'myLevel',
  LEVEL_POLICY: 'level/policy',
  NOTICE_LIST: 'setting/notice',
  TERMS: 'setting/terms',
  GET_NOTIFICATION_INFO: 'get/setting/alarm',
  SET_NOTIFICATION_INFO: 'set/setting/alarm',
};

export const {
  POST,
  COMMENTS,
  LIKE,
  UNLIKE,
  USER_INFO,
  COMMENT_LIKE,
  COMMENT_UNLIKE,
  GET_QUESTION,
  POST_ANSWER,
  MY_LEVEL,
  LEVEL_POLICY,
  NOTICE_LIST,
  TERMS,
  GET_NOTIFICATION_INFO,
  SET_NOTIFICATION_INFO,
} = QUERY_KEYS;
